Secrets:
  - name: "UpstreamClientSecret"
    provider: "Passage.LocalKms"
    reference: "UpstreamClientSecret"
    encryptedValue: "RvrMsvAwJ4W5Pof0CNIuRZxY+/lcYRyQa6gxkoquZqMRFPt67RXiNygN0EUvO+I8ioTxe2WSbg=="
