# NEVER EVER PUT DIRECT SECRETS HERE
# This file is a template for production secrets. It should not contain any actual secrets.
# Instead, it should contain references to secrets.

Secrets:
  - name: "SecretName" # (e.g. DB_PASSWORD)
    provider: "SecretProvider" # (e.g. AWS Secrets Manager)
    reference: "SecretReference" # (e.g. arn:aws:secretsmanager:us-east-1:123456789012:secret:SecretName-123456)

  - name: "OidcClientSecret-ExampleApp"
    provider: "Passage.LocalKms"
    reference: "ExampleAppOidcSecret"
    unencryptedValue: "passage-client-secret"
