Secrets:
  - name: "SecretName"
    provider: "SecretProvider"
    reference: "SecretReference"
  - name: "OidcClientSecret-ExampleApp"
    provider: "Passage.LocalKms"
    reference: "ExampleAppOidcSecret"
    encryptedValue: "Hp8vpQWgpagA3xvkIvMV/DTfIbk2fd7XVyax3ka7Ls0ntv3Gh+iWNnkUBdmiyTIuCKAflT0="
